export const levels = [
  {
    id: 0,
    label: 'Level 0',
    name: 'Foundations',
    shortName: 'Foundations',
    kicker: 'Make the UI render',
    description: 'Build a reliable mental model for JSX, components, props, and the render cycle before adding complexity.',
    time: '1–2 weeks',
    color: 'mint',
    focus: ['JSX and components', 'Props and composition', 'Render and commit'],
    outcomes: [
      'Turn a UI sketch into small, composable function components.',
      'Explain what props are and why render code should stay pure.',
      'Choose stable keys and make simple conditional UI readable.',
    ],
    checkpoint: 'Build a product card list with loading, empty, and error states.',
  },
  {
    id: 1,
    label: 'Level 1',
    name: 'Interactive UI',
    shortName: 'Interaction',
    kicker: 'Make the UI respond',
    description: 'Move from static markup to predictable interactions with state, events, forms, and derived values.',
    time: '2–3 weeks',
    color: 'sky',
    focus: ['State and events', 'Controlled forms', 'Lists and reducers'],
    outcomes: [
      'Model state around the minimum information the UI needs.',
      'Build controlled forms with useful validation and accessible feedback.',
      'Use functional updates and reducers when transitions have structure.',
    ],
    checkpoint: 'Build a searchable, filterable form with optimistic-feeling feedback.',
  },
  {
    id: 2,
    label: 'Level 2',
    name: 'Async React',
    shortName: 'Async',
    kicker: 'Synchronize with the outside world',
    description: 'Handle effects, network states, refs, and custom hooks without turning components into a tangle of timing bugs.',
    time: '2–3 weeks',
    color: 'peach',
    focus: ['Effects and dependencies', 'Fetching states', 'Refs and custom hooks'],
    outcomes: [
      'Separate event logic, render derivations, and external synchronization.',
      'Prevent stale responses and cleanup bugs in async flows.',
      'Extract a custom hook when a behavior has a reusable interface.',
    ],
    checkpoint: 'Build a debounced search flow that handles cancellation and retries.',
  },
  {
    id: 3,
    label: 'Level 3',
    name: 'Application React',
    shortName: 'Application',
    kicker: 'Compose a real product',
    description: 'Organize features around boundaries: shared state, routes, server data, errors, and predictable module ownership.',
    time: '3–4 weeks',
    color: 'violet',
    focus: ['Context and state ownership', 'Routing', 'Server-state boundaries'],
    outcomes: [
      'Keep server state, UI state, and URL state in the right places.',
      'Design context APIs that do not make every consumer rerender by accident.',
      'Explain loading, error, empty, and not-found boundaries across routes.',
    ],
    checkpoint: 'Sketch the architecture for a multi-route dashboard with cached data.',
  },
  {
    id: 4,
    label: 'Level 4',
    name: 'Production React',
    shortName: 'Production',
    kicker: 'Make it fast and resilient',
    description: 'Think beyond the happy path: testing strategy, performance evidence, accessibility, and failure recovery.',
    time: '3–5 weeks',
    color: 'gold',
    focus: ['Testing user behavior', 'Performance diagnosis', 'Accessibility and resilience'],
    outcomes: [
      'Test the behavior users depend on instead of implementation details.',
      'Find the actual expensive work before reaching for memoization.',
      'Design keyboard, screen-reader, and network failure states deliberately.',
    ],
    checkpoint: 'Improve a slow table using a measured hypothesis and a regression test.',
  },
  {
    id: 5,
    label: 'Level 5',
    name: 'React Architect',
    shortName: 'Architect',
    kicker: 'Lead decisions across systems',
    description: 'Communicate trade-offs for large React codebases, teams, migrations, and the server/client boundary.',
    time: 'Ongoing practice',
    color: 'ink',
    focus: ['System boundaries', 'Migration strategy', 'Team-level trade-offs'],
    outcomes: [
      'Compare approaches in terms of ownership, failure modes, and operating cost.',
      'Break a migration into safe, observable slices with rollback points.',
      'Make architecture legible so multiple teams can move without coupling.',
    ],
    checkpoint: 'Lead a design review for a React platform used by several product teams.',
  },
];
