export const scenarios = [
  {
    id: 's0-review',
    level: 0,
    role: 'Junior',
    title: 'The component is doing too much',
    prompt: 'A teammate has one 300-line component that fetches data, renders a table, owns a modal, and formats dates. How do you review it?',
    answer: ['Start with behavior and ownership, not line count.', 'Identify a first seam with a stable interface, such as a table row or modal.', 'Move one responsibility at a time and keep the user-visible behavior covered.', 'Leave a clear follow-up if a full refactor would exceed the change’s risk budget.'],
    followUp: 'What would make you avoid extracting a component?',
    signal: 'Respectful, incremental decomposition.',
  },
  {
    id: 's0-bug',
    level: 0,
    role: 'Junior',
    title: 'A list item shows the wrong checkbox',
    prompt: 'After sorting a list, the checked state appears to move to a different row. Where do you look first?',
    answer: ['Check whether the list uses array indexes as keys.', 'Replace the key with a stable item id if the domain provides one.', 'Explain that React preserves child identity by key across renders.', 'Add a reorder interaction to the regression check.'],
    followUp: 'When is an index key acceptable?',
    signal: 'A concrete identity model and a small reproducible check.',
  },
  {
    id: 's1-form',
    level: 1,
    role: 'Mid-level',
    title: 'A form loses input while typing',
    prompt: 'A controlled form resets a field whenever another field changes. How do you debug the state flow?',
    answer: ['Trace the owner and all setter calls for the reset field.', 'Check whether an effect is copying props into state or whether a key remounts the form.', 'Keep one source of truth and derive display values where possible.', 'Add a user-level test that changes both fields in sequence.'],
    followUp: 'When would you intentionally remount a form with a key?',
    signal: 'Follow the data flow before applying a patch.',
  },
  {
    id: 's1-review',
    level: 1,
    role: 'Mid-level',
    title: 'The PR adds five new state variables',
    prompt: 'A feature adds booleans for loading, success, error, submitting, and hasData. How do you respond in review?',
    answer: ['Look for impossible combinations and transitions that are hard to represent.', 'Suggest a status state or reducer when the values describe one state machine.', 'Keep independent concerns separate when they truly vary independently.', 'Ask for tests around transitions, not just the final happy state.'],
    followUp: 'When is a reducer overkill?',
    signal: 'Model the domain rather than counting hooks.',
  },
  {
    id: 's2-search',
    level: 2,
    role: 'Mid-level',
    title: 'Search results arrive out of order',
    prompt: 'A fast typist sees results for an older query after the newest results. Explain the failure and your fix.',
    answer: ['Each request can resolve in a different order from when it started.', 'Cancel or invalidate the previous request in the effect cleanup.', 'Ignore aborts as expected control flow but surface real failures.', 'Test slow-old plus fast-new responses explicitly.'],
    followUp: 'Would you debounce, cancel, or cache first?',
    signal: 'Correct lifecycle cleanup plus a test for the race.',
  },
  {
    id: 's2-effect',
    level: 2,
    role: 'Mid-level',
    title: 'The effect runs in a loop',
    prompt: 'An effect updates state and then runs again forever. How do you find the unnecessary synchronization?',
    answer: ['List the external system the effect is supposed to synchronize with.', 'If it only derives data from props or state, move that calculation to render.', 'If it responds to a user action, move it to the event handler.', 'If it is a real subscription, make dependencies and cleanup represent that lifecycle.'],
    followUp: 'What does an empty dependency array actually promise?',
    signal: 'Remove the need for the effect before fighting the dependency list.',
  },
  {
    id: 's3-cache',
    level: 3,
    role: 'Senior',
    title: 'Two teams invented two caches',
    prompt: 'The same customer appears stale because separate features each cache their own copy. What architectural move do you propose?',
    answer: ['Map who owns the data and which freshness guarantees users need.', 'Choose a shared server-state boundary with one invalidation model.', 'Keep feature-specific view state local instead of duplicating remote records.', 'Migrate one query path first and measure stale-data reports and request volume.'],
    followUp: 'What if the teams need different projections of the same record?',
    signal: 'A shared ownership and invalidation contract.',
  },
  {
    id: 's3-route',
    level: 3,
    role: 'Senior',
    title: 'A dashboard route is hard to share',
    prompt: 'Filters live in component state, so refreshing or sharing a URL loses the view. How do you redesign it?',
    answer: ['Move shareable filters, pagination, and selected resources into URL params.', 'Parse and validate params at the route boundary with useful defaults.', 'Keep transient UI such as a command menu open state local.', 'Treat browser history behavior as part of the product decision.'],
    followUp: 'Which filters should not be put in the URL?',
    signal: 'URL state serves navigation and collaboration, not every state value.',
  },
  {
    id: 's4-performance',
    level: 4,
    role: 'Senior',
    title: 'Memoization made the screen slower',
    prompt: 'A PR wraps half the tree in memo and adds callbacks everywhere, but interaction got worse. What do you do?',
    answer: ['Reproduce and compare a profile before and after the change.', 'Find whether the bottleneck is render work, layout, network, or bundle cost.', 'Remove memoization that does not prevent expensive work or stabilize a meaningful boundary.', 'Keep only the measured optimization and add a regression signal.'],
    followUp: 'What evidence would justify keeping useMemo?',
    signal: 'Performance work follows evidence and has an exit criterion.',
  },
  {
    id: 's4-a11y',
    level: 4,
    role: 'Senior',
    title: 'The modal passes visual QA but fails keyboard use',
    prompt: 'A modal looks correct but focus escapes behind it and Escape does nothing. How do you lead the fix?',
    answer: ['Reproduce with keyboard-only navigation and define the expected focus lifecycle.', 'Use a semantic dialog with an accessible name and a focus trap appropriate to the product.', 'Return focus to the invoking control on close when it still exists.', 'Add automated checks plus a manual keyboard regression path.'],
    followUp: 'How do you test focus without coupling to implementation details?',
    signal: 'Accessibility is a behavior contract, not a final visual pass.',
  },
  {
    id: 's5-migration',
    level: 5,
    role: 'Staff+',
    title: 'The rewrite has no exit condition',
    prompt: 'A team wants to rewrite the entire frontend before shipping another feature. How do you redirect the plan?',
    answer: ['Clarify the user or business outcome the rewrite is meant to unlock.', 'Choose a vertical slice with real traffic and a compatibility seam.', 'Define success: errors, performance, delivery time, and adoption—not just lines migrated.', 'Instrument the slice and preserve a rollback path before expanding the program.'],
    followUp: 'How do you keep momentum if the first slice exposes a bad assumption?',
    signal: 'Reduce risk through sequencing, observability, and reversible decisions.',
  },
  {
    id: 's5-boundary',
    level: 5,
    role: 'Staff+',
    title: 'Teams disagree on the client boundary',
    prompt: 'One team wants every feature client-rendered; another wants server-first rendering everywhere. How do you facilitate the decision?',
    answer: ['Define the user journeys and constraints before debating defaults.', 'Compare data sensitivity, interactivity, bundle cost, caching, and failure behavior.', 'Agree on a small set of architectural principles and an exception process.', 'Use a pilot route and measure real outcomes before declaring a universal rule.'],
    followUp: 'What would make you revisit the chosen default?',
    signal: 'Good architecture creates guardrails without pretending every route is identical.',
  },
];
